config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'

  resources :articles

  root 'articles#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true,
                    length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1 id="page-title">Editing article</h1>

<%= render 'form' %>

<p><%= link_to 'Back to Index', root_path %></p>

app/views/articles/index.html.erb
<h1 id="page-title">Demonstration Ruby on Rails Application</h1>
<div class="add-article"><%= button_to 'Add article', new_article_path, :method => :get %></div>

<div class="article-list">
  <% @articles.each do |article| %>
    <div class="article">
      <h2 class="title"><%= article.title %></h2>
      <div class="text"><%= simple_format(article.text) %></div>
      <div class="operations" style="visibility: hidden;">
        <%= link_to 'View', article_path(article) %> <%= link_to 'Edit', edit_article_path(article) %> <%= link_to 'Delete', article_path(article),
            method: :delete,
            data: { confirm: 'Are you sure you want to delete this Article?' } %>
      </div>
    </div>
  <% end %>
</div>

<% if @articles.blank? %>
<p><em>There are currently no articles.</em></p>
<% end %>

<p class="app-info">This demonstration is modeled after the official <%= link_to 'Getting Started', 'http://guides.rubyonrails.org/getting_started.html' %> Rails Guide.</p>

app/views/articles/new.html.erb
<h1 id="page-title">New Article</h1>

<%= render 'form' %>

<p><%= link_to 'Back to Index', root_path %></p>

app/views/articles/show.html.erb
<h1 id="page-title"><%= @article.title %></h1>

<div class="article">
  <%= simple_format(@article.text) %>
</div>

<p><%= link_to 'Back to Index', root_path %> | <%= link_to 'Edit', edit_article_path(@article) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demonstration Ruby on Rails Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">

<%= yield %>

</div>
</body>
</html>